//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerSheets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers_tbl
    {
        public long A_ID { get; set; }
        public Nullable<long> q_ID { get; set; }
        public bool states { get; set; }
        public string action { get; set; }
        public bool done { get; set; }
        public long triggerID { get; set; }
        public string TableType { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public Nullable<long> DoneTrigger { get; set; }
    
        public virtual Questions_tbl Questions_tbl { get; set; }
        public virtual Triggers_tbl Triggers_tbl { get; set; }
        public virtual Triggers_tbl Triggers_tbl1 { get; set; }
    }
}
