//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerSheets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_tbl
    {
        public Questions_tbl()
        {
            this.Answers_tbl = new HashSet<Answers_tbl>();
        }
    
        public long Q_ID { get; set; }
        public string question { get; set; }
        public bool AnsType { get; set; }
        public bool Available { get; set; }
        public string TableType { get; set; }
    
        public virtual ICollection<Answers_tbl> Answers_tbl { get; set; }
    }
}
