//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerSheets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary_tbl
    {
        public long Id { get; set; }
        public long TrigID { get; set; }
        public Nullable<bool> SafetyBefore { get; set; }
        public Nullable<bool> SafetyAfter { get; set; }
        public Nullable<bool> QualityBefore { get; set; }
        public Nullable<bool> QualityAfter { get; set; }
        public Nullable<System.DateTime> Inserted { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
    
        public virtual Triggers_tbl Triggers_tbl { get; set; }
    }
}
