//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerSheets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triggers_tbl
    {

        public long TriggerID { get; set; }
        public int line { get; set; }
        public string shift { get; set; }
        public System.DateTime daydate { get; set; }
        public Nullable<long> usernum { get; set; }
    
        public virtual ICollection<Answers_tbl> Answers_tbl { get; set; }
        public virtual ICollection<Answers_tbl> Answers_tbl1 { get; set; }
        public virtual ICollection<Summary_tbl> Summary_tbl { get; set; }
    }
}
