//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerSheets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Line
    {
        public long ID { get; set; }
        public string User_num { get; set; }
        public string Name { get; set; }
        public Nullable<int> Line { get; set; }
        public string Type { get; set; }
    }
}
